version: '3'
services:
  build:
    build:
      context: ./Build
      dockerfile: Dockerfile
    image: build
    ports:
      - "8013:8080"
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test
      MYSQL_PASSWORD: test
    ports:
      - "8001:3306"
    expose:
      - "3306"