version: '3'
services:
  build:
    build:
      context: ./Build
      dockerfile: Dockerfile
    image: build
    ports:
      - "8013:8080"
    depends_on:
      - mysqltest

  mysqltest:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: test
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - ./data:/var/lib/mysql
